name = "MTR LetsPlay Server Modpack"
author = "Zbx1425"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9739a16e98862a609172f771afdd332f75004f4c4428cae876375871416ad839"

[versions]
fabric = "0.18.4"
minecraft = "1.20.4"
