name = "MTR LetsPlay Server Modpack"
author = "Zbx1425"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d8aec8472dab0b1c1c1e6a1138eaf2ebfded79b6b3fb2994a03792ce132d176e"

[versions]
fabric = "0.18.4"
minecraft = "1.20.4"
