name = "MTR LetsPlay Server Modpack"
author = "Zbx1425"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f555c08d50436a7c4b1db450066311e5eadab15d234c71b4c5e5ede929774b99"

[versions]
fabric = "0.18.4"
minecraft = "1.20.4"
